spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/postgres?createDatabaseIfNotExist=true
    username: postgres
    password: example
